export type Session={start:number;end:number;title:string;lanes:string;price:number|null};
export type Schedule={status:'published'|'unknown'|'closed'|'unlisted';sessions:Session[];note:string;source:string;checkedAt:string;live?:boolean};
export type Pool={id:string;name:string;subtitle:string;area:'ma'|'va';town:string;address:string;phone:string;length:string;lengths:string[];lengthNote:string;price:number;residentPrice?:number;priceLabel:string;priceNote:string;website:string;scheduleUrl:string;laneUrl?:string;priceUrl:string;lengthUrl:string;access:string;notes:string};
const rates='https://www.fairfaxcounty.gov/parks/passes';
const dimensions='https://www.fairfaxcounty.gov/cregister/DownloadPDF.aspx?AttachmentID=1174667f-3af6-42ee-ae57-b6c1f4a99f05';
export const pools:Pool[]=[
{id:'cra',name:'Boston Sports Institute',subtitle:'Charles River Aquatics · Competition pool',area:'ma',town:'Wellesley, MA',address:'900 Worcester Street, Wellesley, MA 02482',phone:'617-939-8078',length:'25 yards',lengths:['25y'],lengthNote:'13-lane competition pool; the number assigned to lap swimming varies.',price:8,priceLabel:'from / swim',priceNote:'Community: $8 per swim, age 14+. Premium: $20 per swim. Buy a punch pass and reserve before arrival. These are per-session prices, not all-day admission.',website:'https://charlesriveraquatics.com/lap-swim-program/',scheduleUrl:'https://charlesriveraquatics.com/lap-swim-schedule/',priceUrl:'https://charlesriveraquatics.com/lap-swim-program/',lengthUrl:'https://charlesriveraquatics.com/lap-swim-program/',access:'Reservation required',notes:'Premium sessions provide a lane for one swimmer; community sessions use shared lanes. A published calendar entry does not confirm remaining booking capacity.'},
{id:'longfellow',name:'Longfellow Wellesley',subtitle:'Tennis & Health Club · Indoor pool',area:'ma',town:'Wellesley, MA',address:'140 Great Plain Avenue, Wellesley, MA',phone:'781-705-2300',length:'Length unconfirmed',lengths:[],lengthNote:'The official club page lists six indoor lanes but does not state their length.',price:35,priceLabel:'/ guest visit',priceNote:'$35 unaccompanied guest visit; $25 with a member. Photo ID required. Limit four guest visits per year. Confirm pool access before paying.',website:'https://www.longfellowhealthclubs.com/wellesley',scheduleUrl:'https://www.longfellowhealthclubs.com/wellesley',priceUrl:'https://www.longfellowhealthclubs.com/membership-and-guest-policies',lengthUrl:'https://www.longfellowhealthclubs.com/wellesley',access:'Guest restrictions',notes:'Older pool schedules appear in search results. We have not treated those as current or used them to promise a swim time.'},
{id:'spring',name:'Spring Hill Rec Center',subtitle:'Fairfax County Park Authority',area:'va',town:'McLean, VA',address:'1239 Spring Hill Road, McLean, VA 22102',phone:'703-827-0989',length:'25 yd × 25 m',lengths:['25y','25m'],lengthNote:'Pool dimensions; the lane direction in use may vary. Confirm the current course length.',price:14,residentPrice:11,priceLabel:'/ adult visit',priceNote:'Adults 19–64: $11 Fairfax County resident or $14 nonresident. Youth, students and seniors have separate rates. Single entry; no re-entry.',website:'https://www.fairfaxcounty.gov/parks/reccenter/spring-hill',scheduleUrl:'https://www.fairfaxcounty.gov/parks/sites/parks/files/assets/documents/recenters/calendars/shillpool.pdf',priceUrl:rates,lengthUrl:dimensions,access:'Public day admission',notes:'September calendar provides at least three public lap lanes while open. Shared lanes; lessons and rentals reduce space.'},
{id:'providence',name:'Providence Rec Center',subtitle:'Fairfax County Park Authority',area:'va',town:'Falls Church, VA',address:'7525 Marc Drive, Falls Church, VA 22042',phone:'703-698-1351',length:'25 yd × 25 m',lengths:['25y','25m'],lengthNote:'Pool dimensions; confirm which lane direction is in use.',price:14,residentPrice:11,priceLabel:'/ adult visit',priceNote:'Adults 19–64: $11 Fairfax County resident or $14 nonresident. Youth, students and seniors have separate rates. Single entry; no re-entry.',website:'https://www.fairfaxcounty.gov/parks/reccenter/providence',scheduleUrl:'https://www.fairfaxcounty.gov/parks/sites/parks/files/Assets/documents/recenters/calendars/provpool.pdf',priceUrl:rates,lengthUrl:dimensions,access:'Public day admission',notes:'September calendar provides at least three public lap lanes while open. Suggested lap times: weekdays before 3:30 pm and weekends after 1 pm.'},
{id:'oakmont',name:'Oakmont Rec Center',subtitle:'Fairfax County Park Authority',area:'va',town:'Oakton, VA',address:'3200 Jermantown Road, Oakton, VA 22124',phone:'703-281-6501',length:'25 yd × 75 m facility',lengths:['25y'],lengthNote:'Facility dimensions include multiple pool areas. A 50 m lap setup is not verified here; confirm the current configuration.',price:14,residentPrice:11,priceLabel:'/ adult visit',priceNote:'Adults 19–64: $11 Fairfax County resident or $14 nonresident. Youth, students and seniors have separate rates. Single entry; no re-entry.',website:'https://www.fairfaxcounty.gov/parks/reccenter/oakmont',scheduleUrl:'https://www.fairfaxcounty.gov/parks/sites/parks/files/Assets/documents/recenters/calendars/ompool.pdf',priceUrl:rates,lengthUrl:dimensions,access:'Public day admission',notes:'Pool maintenance closure August 29–September 8, 2026. Reopening scheduled September 9. September calendar provides at least three public lap lanes while open.'}
];
const apsSchedule='https://www.apsva.us/wp-content/uploads/sites/57/2026/08/School-Year-Schedule_2027.pdf';
const apsPools='https://www.apsva.us/aquatics/aps-pools/';
const apsFees='https://www.apsva.us/wp-content/uploads/sites/57/2026/08/26-27-AQUATICS-FEES.pdf';
pools.push(
{id:'yorktown',name:'Yorktown Aquatics Center',subtitle:'Arlington Public Schools · Community swimming',area:'va',town:'Arlington, VA',address:'5200 Yorktown Boulevard, Arlington, VA 22207',phone:'703-228-8754',length:'25 yards',lengths:['25y'],lengthNote:'Eight-lane competition pool, plus separate instructional and diving areas.',price:13.55,priceLabel:'/ adult swim',priceNote:'Published July 2026 fees: $13.55 non-Arlington adult swim; $9.50 Arlington resident adult. Separate youth and senior rates. Visa/MasterCard accepted; no cash. Bring photo ID for entry.',website:apsPools,scheduleUrl:apsSchedule,laneUrl:'https://www.apsva.us/wp-content/uploads/sites/57/2026/09/Lane-Availability-YT-2025-26.pdf',priceUrl:apsFees,lengthUrl:apsPools,access:'Public swim · photo ID',notes:'Enter through door 3 off Greenbriar Street. The men’s locker room is closed as of the September 4 check; use individual changing rooms. No Friday evening swim. Lane chart is headed 2026–2027 despite the older filename.'},
{id:'washington',name:'Washington-Liberty Aquatics',subtitle:'Arlington Public Schools · Community swimming',area:'va',town:'Arlington, VA',address:'1301 N. Stafford Street, Arlington, VA 22201',phone:'703-228-6262',length:'25 yd × 25 m',lengths:['25y','25m'],lengthNote:'Main pool dimensions; confirm the lane direction in use. Separate instructional and diving areas.',price:13.55,priceLabel:'/ adult swim',priceNote:'Published July 2026 fees: $13.55 non-Arlington adult swim; $9.50 Arlington resident adult. Separate youth and senior rates. Visa/MasterCard accepted; no cash. Bring photo ID for entry.',website:apsPools,scheduleUrl:apsSchedule,laneUrl:'https://www.apsva.us/wp-content/uploads/sites/57/2026/09/Lane-Availability-WL-2025-26.pdf',priceUrl:apsFees,lengthUrl:apsPools,access:'Public swim · photo ID',notes:'Enter through door 7. Friday evening water polo uses some lanes; the lane chart shows remaining lap space. Some lockers are unavailable during school hours. Lane chart is headed 2026–2027 despite the older filename.'},
{id:'audrey',name:'Audrey Moore Rec Center',subtitle:'Fairfax County Park Authority',area:'va',town:'Annandale, VA',address:'8100 Braddock Road, Annandale, VA 22003',phone:'703-321-7081',length:'50 m × 25 yd',lengths:['25y','50m'],lengthNote:'The facility supports long and short course configurations. These change by date and time; check the lane chart for a 50 m session.',price:14,priceLabel:'/ adult visit',priceNote:'Adults 19–64: $14 nonresident or $11 Fairfax County resident. Youth, students and seniors have separate rates. Single entry; no re-entry.',website:'https://www.fairfaxcounty.gov/parks/reccenter/audrey-moore',scheduleUrl:'https://www.fairfaxcounty.gov/parks/sites/parks/files/Assets/documents/recenters/calendars/wakepool.pdf',priceUrl:rates,lengthUrl:'https://www.fairfaxcounty.gov/parks/sites/parks/files/Assets/documents/Administrative/recenter-systemwide-sustainability-plan.pdf',access:'Public day admission',notes:'September calendar provides at least three public lap lanes while open. Evening lessons and teams reduce space; the PDF includes daily lane diagrams. Longer drive from McLean than Spring Hill.'}
);
export const checkedAt='2026-09-04T22:40:00Z';
export function validDate(date:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return false;const d=new Date(date+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===date;}
export function easternToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export function clock(minutes:number){const h=Math.floor(minutes/60);return `${h%12||12}:${String(minutes%60).padStart(2,'0')} ${h>=12?'pm':'am'}`;}
export function visitPrice(p:Pool,resident:boolean){return resident&&p.residentPrice!==undefined?p.residentPrice:p.price;}
export function baseSchedule(p:Pool,date:string):Schedule{
 const base={sessions:[] as Session[],source:p.scheduleUrl,checkedAt};
 if(p.id==='cra')return {...base,status:'unknown',note:'Checking the official lap-swim calendar…'};
 if(p.id==='longfellow')return {...base,status:'unknown',note:'Current dated lap schedule and holiday exceptions not verified. Call the club.'};
 if(p.id==='yorktown'||p.id==='washington'){
  const major=['2026-11-26','2026-12-25','2027-01-01','2027-03-28'];
  const special=['2026-09-07','2026-11-11','2027-01-18','2027-02-15','2027-05-31','2027-06-18'];
  if(major.includes(date)||(special.includes(date)&&p.id==='yorktown'))return {...base,status:'closed',note:'Closed for this holiday on the APS 2026–2027 public swim schedule.'};
  if(special.includes(date))return {...base,status:'published',sessions:[{start:360,end:1080,title:'Holiday public swim',lanes:'Holiday lane allocation: confirm',price:13.55}],note:'Holiday exception: Washington-Liberty opens 6 am–6 pm while Yorktown is closed. Check lane availability with the pool.'};
  if(date<'2026-08-31'||date>'2027-06-17')return {...base,status:'unknown',note:'The checked APS schedule covers August 31, 2026–June 17, 2027. Confirm this date with the pool.'};
  const day=new Date(date+'T12:00:00Z').getUTCDay();const yt=p.id==='yorktown';
  const windows=day===0?(yt?[[600,1020]]:[[720,1020]]):day===6?(yt?[[360,1020]]:[[360,1140]]):yt?(day===5?[[330,510],[750,870]]:[[330,510],[750,870],[1080,1230]]):(day===5?[[330,570],[750,900],[1080,1200]]:[[330,570],[750,900],[1080,1230]]);
  return {...base,status:'published',sessions:windows.map(([start,end])=>({start,end,title:'Public lap swimming',lanes:yt?'Typical 2–8 lanes; see lane chart':day===5&&start===1080?'3 lap lanes shown; water polo in other lanes':'Lane count varies; see lane chart',price:13.55})),note:'APS school-year schedule and 2026–2027 lane chart. Holiday exceptions override these hours. Lane allocations can change at staff discretion.'};
 }
 if(date>='2026-08-29'&&date<='2026-09-08'&&p.id==='oakmont')return {...base,status:'closed',note:'Pool closed for maintenance through September 8. Scheduled reopening: September 9, 2026.'};
 if(date<'2026-09-01'||date>'2026-09-30')return {...base,status:'unknown',note:'The checked PDF covers September 2026 only. Open the latest schedule or call to confirm this date.'};
 const day=new Date(date+'T12:00:00Z').getUTCDay();const weekend=day===0||day===6;let start=weekend?(p.id==='oakmont'?480:540):390;let end=weekend?1080:1260;
 let note='September 2026 schedule. At least 3 lanes are designated for public lap swimming; this is not a count of empty lanes.';
 if(date==='2026-09-07'){end=1080;note='Labor Day exception: pool closes at 6 pm. Holiday hours override the regular Monday schedule.';}
 if(p.id==='providence'&&(date==='2026-09-05'||date==='2026-09-06')){start=570;note='Labor Day weekend exception: published swim hours start at 9:30 am, not 9 am.';}
 return {...base,status:'published',sessions:[{start,end,title:'Public lap swimming',lanes:'3+ designated lap lanes',price:null}],note};
}
export type Filters={area:string;query:string;date:string;time:string;length:string;budget:string;duration:string};
export function defaults():Filters{return {area:'all',query:'',date:easternToday(),time:'',length:'any',budget:'any',duration:'30'};}
export function matchingSessions(s:Schedule,f:Filters,p:Pool){const duration=Number(f.duration);const target=f.time?Number(f.time.slice(0,2))*60+Number(f.time.slice(3,5)):null;const max=f.budget==='any'?Infinity:Number(f.budget);return s.sessions.filter(x=>{const price=x.price??visitPrice(p,false);if(price>max)return false;const start=target===null?x.start:Math.max(x.start,target-60);const latest=target===null?x.end-duration:Math.min(target+60,x.end-duration);return start<=latest;});}
export function poolMatches(p:Pool,f:Filters){return (f.area==='all'||p.area===f.area)&&(!f.query||`${p.name} ${p.town} ${p.address}`.toLowerCase().includes(f.query.toLowerCase().trim()))&&(f.length==='any'||p.lengths.includes(f.length))&&(f.budget==='any'||visitPrice(p,false)<=Number(f.budget));}
export type Alternative={date:string;start:number;end:number;price:number;distance:number};
export function closestSwim(p:Pool,f:Filters,s:Schedule):Alternative|null{
 if(!f.time)return null;
 const target=Number(f.time.slice(0,2))*60+Number(f.time.slice(3));const duration=Number(f.duration);const max=f.budget==='any'?Infinity:Number(f.budget);const candidates:Alternative[]=[];
 for(let offset=0;offset<=7;offset++){
  const d=new Date(f.date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+offset);const date=d.toISOString().slice(0,10);
  // Only searched calendar events can substantiate CRA alternatives. Static schedules expire at their stated end dates.
  if(offset>0&&p.id==='cra')break;
  const schedule=offset===0?s:baseSchedule(p,date);if(schedule.status!=='published')continue;
  for(const session of schedule.sessions){if(p.id==='cra'&&session.price===null&&max!==Infinity)continue;const price=session.price??visitPrice(p,false);if(price>max||session.end-session.start<duration)continue;
   const start=offset===0?Math.max(session.start,Math.min(target,session.end-duration)):session.start;
   candidates.push({date,start,end:start+duration,price,distance:Math.abs(offset*1440+start-target)});
  }
 }
 return candidates.sort((a,b)=>a.distance-b.distance||a.start-b.start)[0]??null;
}

